export const rankData = [{
    delegation: '代表队1',
    tRank: 1,
    staffName: '队员1',
    score: 98,
    departmentName: '杭州代表队'
  }, {
    delegation: '代表队2',
    tRank: 1,
    staffName: '队员1',
    score: 96,
    departmentName: '温州代表队'
  }, {
    delegation: '代表队3',
    tRank: 1,
    staffName: '队员1',
    score: 94,
    departmentName: '嘉兴代表队'
  }, {
    delegation: '代表队4',
    tRank: 1,
    staffName: '队员1',
    score: 86,
    departmentName: '湖州代表队'
  }, {
    delegation: '代表队5',
    tRank: 1,
    staffName: '队员1',
    score: 84,
    departmentName: '衢州代表队'
  }, {
    delegation: '代表队6',
    tRank: 1,
    staffName: '队员1',
    score: 82,
    departmentName: '绍兴代表队'
  }, {
    delegation: '代表队7',
    tRank: 1,
    staffName: '队员1',
    score: 80,
    departmentName: '金华代表队'
  }, {
    delegation: '代表队8',
    tRank: 1,
    staffName: '队员1',
    score: 70,
    departmentName: '丽水代表队'
  }, {
    delegation: '代表队9',
    tRank: 1,
    staffName: '队员1',
    score: 66,
    departmentName: '义乌代表队'
  }, {
    delegation: '代表队10',
    tRank: 1,
    staffName: '队员1',
    score: 64,
    departmentName: '嘉兴代表队'
  }, {
    delegation: '代表队11',
    tRank: 1,
    staffName: '队员1',
    score: 62,
    departmentName: '诸暨代表队'
  }, {
    delegation: '代表队12',
    tRank: 1,
    staffName: '队员1',
    score: 60,
    departmentName: '湖州代表队'
  }]