export const defalutData = [{
    delegation: '代表队1',
    tRank: 1,
    staffName: '队员1',
    score: 98,
    staffId: '100',
    departmentName: '杭州代表队'
  }, {
    delegation: '代表队2',
    tRank: 2,
    staffName: '队员2',
    score: 96,
    staffId: '101',
    departmentName: '温州代表队'
  }, {
    delegation: '代表队3',
    tRank: 3,
    staffName: '队员3',
    score: 94,
    staffId: '102',
    departmentName: '嘉兴代表队'
  }, {
    delegation: '代表队4',
    tRank: 4,
    staffName: '队员4',
    score: 86,
    staffId: '103',
    departmentName: '湖州代表队'
  }, {
    delegation: '代表队5',
    tRank: 5,
    staffName: '队员5',
    score: 84,
    staffId: '104',
    departmentName: '衢州代表队'
  }, {
    delegation: '代表队6',
    tRank: 6,
    staffName: '队员6',
    score: 82,
    staffId: '105',
    departmentName: '绍兴代表队'
  }, {
    delegation: '代表队7',
    tRank: 7,
    staffName: '队员7',
    score: 80,
    staffId: '106',
    departmentName: '金华代表队'
  }, {
    delegation: '代表队8',
    tRank: 8,
    staffName: '队员8',
    score: 70,
    staffId: '107',
    departmentName: '丽水代表队'
  }, {
    delegation: '代表队9',
    tRank: 9,
    staffName: '队员9',
    score: 66,
    staffId: '108',
    departmentName: '义乌代表队'
  }, {
    delegation: '代表队10',
    tRank: 10,
    staffName: '队员11',
    score: 64,
    staffId: '109',
    departmentName: '嘉兴代表队'
  }, {
    delegation: '代表队11',
    tRank: 11,
    staffName: '队员12',
    score: 62,
    staffId: '110',
    departmentName: '诸暨代表队'
  }, {
    delegation: '代表队12',
    tRank: 12,
    staffName: '队员13',
    score: 60,
    staffId: '111',
    departmentName: '湖州代表队'
  }]